### ISSUE TITLE
Download/Install of Xquatz 2.8.0 completed but fails

### ISSUE THREAD

**Issue by prowat** [XQuartz/XQuartz#149] opened 2021-04-04 21:14 UTC
After download and install, "About XQuartz" still says I have 2.8.0_beta3.

What's up?
Is there a way to figure out if I really have the new Xquartz 2.8.0 ?

**Comment by jeremyhu** [comment] 2021-04-04 21:54
Dupe of #88.  Please manually install from http://xquartz.org

**Closed** 2021-04-04 21:54 UTC

**Comment by prowat** [comment] 2021-04-04 23:05
I did that, with the same result. (went to quartz.org<http://quartz.org>, downloaded the .dmg file, opened, installed it, but again got the message that I was using 2.8.0_beta3)

Peter Rowat
MacOS Catalina 10.15.7

On Apr 4, 2021, at 2:54 PM, Jeremy Huddleston Sequoia ***@***.******@***.***>> wrote:



Dupe of #88<https://urldefense.com/v3/__https://github.com/XQuartz/XQuartz/issues/88__;!!Mih3wA!Rd6TnJ1CFWH5uMGRXhkoJgX84D2wiCWamT4Zg8ltl1M69_hn11X9b661T7ABrp4$>. Please manually install from http://xquartz.org<https://urldefense.com/v3/__http://xquartz.org__;!!Mih3wA!Rd6TnJ1CFWH5uMGRXhkoJgX84D2wiCWamT4Zg8ltl1M69_hn11X9b661-IesSbo$>

**Comment by jeremyhu** [comment] 2021-04-06 18:05
Then I suggest asking for help on the x11-users mailing list.  Please provide your /var/log/install.log

**Comment by jeremyhu** [comment] 2021-04-06 18:06
Also... you did quit and re-launch XQuartz.app, right... ?
