### ISSUE TITLE
no x windows display

### ISSUE THREAD

**Issue by n00mad** [XQuartz/XQuartz#96] opened 2021-02-27 13:28 UTC
after  updating to rc1 on sierra and beta4 on mojave, no x windows  display.  xquartz starts ok. and will quit ok.  but no x windows appear.  no error messages appear.  no new windows appear in drop down menu.

**Comment by jeremyhu** [comment] 2021-02-27 15:34
Can you be more specific?  What windows do you expect to see?  How are you launching the applications that create those windows?  Are they local on the mac or client apps on another system?  Do you have fullscreen mode enabled?

**Comment by n00mad** [comment] 2021-02-27 19:34
installed 2.7.11 and that works.

xclock from local command line was base line test

the two other apps are from ssh tunnels.   one is zenmap   and other is sguil.tk that is part of security onion.  been using xquartz for them for several years.

i'm not x11 knowledgeable, so i'm not sure what fullscreen mode enabled would mean.   using built in monitor on an imac.   the apps do not come in as full screen windows in other desktops/spaces.  they appear within the xquartz app and i enlarge them but within a single desktop/space.

**Comment by jeremyhu** [comment] 2021-02-27 21:52
By fullscreen mode, I mean the option in Preferences -> Output labled "Full-screen mode"

**Comment by n00mad** [comment] 2021-02-27 22:00
the full-screen mode preference was not enabled

**Comment by jeremyhu** [comment] 2021-03-01 06:58
Are you by chance seeing the same thing a the person in #97?  Does xclock run and show nothing, or just terminate immediately?

**Comment by dmerget** [comment] 2021-03-01 07:08
I'm experiencing a similar issue as n00mad.  After updating to 2.8.0_rc2, I couldn't open any windows.  The main window I use is Terminal (which I believe is an xterm).  I tried clicking Applications->Terminal both from the main menu and from the pop-up menu obtained by right-clicking the "X" icon in the dock.  In addition, the terminal window that normally pops up when I launch XQuartz did not appear.

I tried opening the other two apps in the  Applications menu (xman & xlogo).  They also displayed nothing, although in fairness I'm not sure what they normally do.  I would've tried other X programs I'm more familiar with such as gvim, but I normally launch them from the Terminal command line, so I'm a bit hobbled without the Terminal.

I tried doing a clean install by uninstalling the previous XQuartz and removing my custom .Xmodmap, .Xresources, and .xinitrc.d from my home dir.  Then I rebooted and installed rc1 from scratch.  This did not improve matters.

I don't have "Full-screen mode" enabled.

I've currently uninstalled the update and re-installed 2.8.0_beta3, which works fine.

My system:
macOS Big Sur version 11.2.2
MacBook Pro (Retina, 15-inch, Late 2013)
Processor 2.6 GHz Quad-Core Intel Core i7
Memory 16 GB 1600 MHz DDR3
Graphics NVIDIA GeForce GT 750M 2 GB.

**Comment by dmerget** [comment] 2021-03-01 07:22
Update: I just followed jeremyhu's link to  #97 (which arrived while I was typing my previous comment), and rc2 now works after I followed the suggestion of removing /opt/X11.  Previously, I had uninstalled XQuartz by merely dragging XQuartz.app to the trash bin, but I hadn't touched /opt/X11.  So the key seems to be to uninstall XQuartz.app *AND* remove /opt/X11.

**Comment by n00mad** [comment] 2021-03-01 19:36
I updated to rc2 on a remote mojave / macmini. the xquartz xterm now works along with xclock from that xterm.   i've 
got a remaining anomaly that iterm2 xclock does not display.  you can close this ticket if you want as I cannot 
update or restart iterm2  on the remote machine with disrupting some production office work.  it will be weeks 
before I can get physical access to the machine to update iterm2 and reset the production configurations.  so i've gone back to 2.7.11 on both sierra and mojave and have all the functionality i need.  Thanks!

**Comment by jeremyhu** [comment] 2021-03-04 06:14
Ok, let's leave this as a dupe of #97 then.  Do you happen to have your old /opt/X11 archived or know how it came to have what it had in it that was conflicting?  Was it the same /opt/X11/share/fonts/fonts symlink?

**Closed by jeremyhu** 2021-03-04 06:14 UTC
Labels: Need Info
