### ISSUE TITLE
windows is oversize in OSX 

### ISSUE THREAD

**Issue by elcolie** [XQuartz/XQuartz#153] opened 2021-04-09 09:37 UTC
OSX: `10.15.7 (19H15)`
`XQuartz 2.8.0_beta3 (xorg-server 1.19.7)`

I have 2 extended 27 inch monitors. Everything went fine until I remote to my server and run `Chromium`. Browser starts with full size window and unfortunately bottom-right aka resizing corner is not fit the screen

**Question:**<br>
What is workaround to resize my window?

**Comment by jeremyhu** [comment] 2021-04-09 21:59
Window sizing is controled by the client.  The only way to do it from quartz-wm is the drag icon.

Please install 2.8.0 final (or 2.8.1_beta1) manually as the 2.8.0_beta3 updater didn't work correctly.

Dupe of #92

**Closed by jeremyhu** 2021-04-09 21:59 UTC
