### ISSUE TITLE
Fonts fail to render in GTK applications

### ISSUE THREAD

**Issue by franzinc** [XQuartz/XQuartz#121] opened 2021-03-12 19:50 UTC
My application does not display properly (all characters are block outlines) in 2.8.0_rc3 (a customer alerted me to this fact).  When I downgrade to 2.7.11 by running the pkg file, logout, login again, my app doesn't even display a window now.

When I quit XQuartz it restarts.

Ideas?

**Comment by franzinc** [comment] 2021-03-12 20:05
![Screen Shot 2021-03-12 at 12 04 43 PM](https://user-images.githubusercontent.com/84627/110992725-299e3a80-832b-11eb-903b-6e195f7ba2f0.png)

The above is how my application looks with 2.8.0_rc3

**Comment by franzinc** [comment] 2021-03-12 20:05
This is on Mojave, fully updated today.

**Comment by TomShultz** [comment] 2021-03-12 20:06
I have these same issues.

**Comment by franzinc** [comment] 2021-03-12 20:06
I'm hoping for two things: a fix for 2.8.0 and a way to temporarily get back to 2.7.11.

Thanks.

**Comment by TomShultz** [comment] 2021-03-12 20:08
I have these same issues with versions 2.8.0 and 2.7.11

**Comment by franzinc** [comment] 2021-03-12 20:08
One last bit of info: between the app and XQuartz is our own GTK Framework.

[https://franz.com/ftp/pub/macosx/GTK+-Framework-2.24.pkg](https://franz.com/ftp/pub/macosx/GTK+-Framework-2.24.pkg)

It has worked flawlessly for years, through many upgrades of XQuartz.

**Comment by jeremyhu** [comment] 2021-03-12 20:12
You need to uninstall 2.8.0 per the instructions at https://www.xquartz.org/FAQs.html prior to downgrading to 2.7.11.  After installing 2.7.11, please reboot.

Was this working when you upgraded from 2.7.11 to 2.8.0_rc2?  rc2 left libcairo present from 2.7.11.  rc3 now removes it.  If your GTK was dependent on XQuartz-vended cairo, maybe that was part of the problem.  If that's the case, I could look at re-adding cairo.  I removed it because I thought nothing was depending on it.

**Comment by franzinc** [comment] 2021-03-12 20:16
> You need to uninstall 2.8.0 per the instructions at https://www.xquartz.org/FAQs.html prior to downgrading to 2.7.11. After installing 2.7.11, please reboot.

Thanks, for that pointer. I will do that now and report back.

> 
> Was this working when you upgraded from 2.7.11 to 2.8.0_rc2? rc2 left libcairo present from 2.7.11. rc3 now removes it. If your GTK was dependent on XQuartz-vended cairo, maybe that was part of the problem. If that's the case, I could look at re-adding cairo. I removed it because I thought nothing was depending on it.

If we use libcairo it would be indirectly, however, I remember it was built into the GTK framework.  Not sure how to check that now, though.

**Comment by franzinc** [comment] 2021-03-12 20:18
Note that the block outline behavior is what we usually see when upgrading macOS without reinstalling (even the same version of) XQuartz.  I don't know if that's related.

**Comment by franzinc** [comment] 2021-03-12 20:21
> Was this working when you upgraded from 2.7.11 to 2.8.0_rc2?

I never tried that version.

**Comment by franzinc** [comment] 2021-03-12 20:22
If you want me to try rc2 I can.

**Comment by franzinc** [comment] 2021-03-12 20:23
Happy to report 2.7.11 works after following the 2.8.0 uninstall instructions in the FAQ and rebooting.  Thanks.

**Comment by jeremyhu** [comment] 2021-03-12 20:30
Ok, well that's good to get you back in a functioning state, but it would be good to fix the issue with 2.8.  Can you please help identify what migh be causing the issue?  Or can you provide me with a reproduction case?

**Comment by franzinc** [comment] 2021-03-12 21:20
The reproduce the failure, after 2.8.0_rc3 is installed:

* Download and install 

https://franz.com/ftp/pub/macosx/GTK+-Framework-2.24.pkg

* Download and install

https://franz.com/ftp/pub/acl10.1express/macosx86/acl10.1express-macosx-x64.dmg

* Run /Applications/AllegroCL64express.app

Let me know if you have questions.

**Comment by franzinc** [comment] 2021-03-12 21:30
Thanks for all the help @jeremyhu

**Comment by jeremyhu** [comment] 2021-03-15 15:43
It looks like your app is using its own set of X11 client libraries:

[1047] /Applications $ otool -L /Library/Frameworks/Gtk.framework/Libraries/libgtk-x11-2.0.0.dylib 
/Library/Frameworks/Gtk.framework/Libraries/libgtk-x11-2.0.0.dylib (architecture i386):
	/Library/Frameworks/Gtk.framework/Libraries/libgtk-x11-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.24.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgdk-x11-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.24.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXinerama.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXi.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXrandr.2.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXcursor.1.dylib (compatibility version 2.0.0, current version 2.2.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgmodule-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpangocairo-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXcomposite.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXdamage.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXfixes.3.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libxcb.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXau.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXdmcp.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libatk-1.0.0.dylib (compatibility version 21210.0.0, current version 21210.1.0)
	/Library/Frameworks/Gtk.framework/Libraries/libcairo.2.dylib (compatibility version 11203.0.0, current version 11203.16.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgdk_pixbuf-2.0.0.dylib (compatibility version 3001.0.0, current version 3001.8.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgio-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpangoft2-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpango-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgobject-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libglib-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib (compatibility version 10.0.0, current version 10.2.0)
	/Library/Frameworks/Gtk.framework/Libraries/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libfreetype.6.dylib (compatibility version 18.0.0, current version 18.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
/Library/Frameworks/Gtk.framework/Libraries/libgtk-x11-2.0.0.dylib (architecture x86_64):
	/Library/Frameworks/Gtk.framework/Libraries/libgtk-x11-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.24.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgdk-x11-2.0.0.dylib (compatibility version 2401.0.0, current version 2401.24.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXinerama.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXi.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXrandr.2.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXcursor.1.dylib (compatibility version 2.0.0, current version 2.2.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgmodule-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpangocairo-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXcomposite.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXdamage.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXfixes.3.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libxcb.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXau.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libXdmcp.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libatk-1.0.0.dylib (compatibility version 21210.0.0, current version 21210.1.0)
	/Library/Frameworks/Gtk.framework/Libraries/libcairo.2.dylib (compatibility version 11203.0.0, current version 11203.16.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgdk_pixbuf-2.0.0.dylib (compatibility version 3001.0.0, current version 3001.8.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgio-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpangoft2-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libpango-1.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	/Library/Frameworks/Gtk.framework/Libraries/libgobject-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libglib-2.0.0.dylib (compatibility version 4001.0.0, current version 4001.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libintl.8.dylib (compatibility version 10.0.0, current version 10.2.0)
	/Library/Frameworks/Gtk.framework/Libraries/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/Library/Frameworks/Gtk.framework/Libraries/libfreetype.6.dylib (compatibility version 18.0.0, current version 18.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)

**Comment by franzinc** [comment] 2021-03-15 15:48
Yes.  That work was done a long time ago by someone that doesn't work at the company any longer.  Are you saying the old libraries are the cause and are incompatible with the new XQuartz?

I don't know the reasoning of why the libraries were packaged in that way.  Probably for ease of use by our customers, I imagine.

**Comment by jeremyhu** [comment] 2021-03-15 15:52
It looks like you've configured your fontconfig to find font configuration data from /opt/local:

(08:45:50 Mon Mar 15 2021 jeremy@tair ttys000 arm64)
[1056] /Library/Frameworks/Gtk.framework/Libraries $ strings libfontconfig.1.dylib.bak| grep opt
/opt/local/etc/fonts
/opt/local/var/cache/fontconfig
/opt/local/etc/fonts
/opt/local/var/cache/fontconfig

---

I tried swapping out your X11 librraies with the ones from XQuartz as my hunch is that if you use the system libraries, it'd be fine:

[1064] /Library/Frameworks/Gtk.framework/Libraries $ for f in *
do
if [[ -f /opt/X11/lib/$f ]] ; then
sudo mv $f $f.bak
sudo ln -s /opt/X11/lib/$f
fi
done

---

However, when I do that, I get a message on launch that the GTK framework is damaged, so I wasn't really able to test much.

Do you know how I can get past that message or atleast figure out why it doesn't like my modifications?

**Comment by jeremyhu** [comment] 2021-03-15 16:25
I figured out how to bypass that check.

If I open up Terminal and run ` /Applications/AllegroCL64express.app/Contents/Resources/allegro-express`, the fonts render fine.  So it looks like an issue with your Gtk.framework.  I suspect it has to do with your font caching.

**Comment by jeremyhu** [comment] 2021-03-15 16:30
Yep, I retested.  This time only replacing your libfontconfig.1.dylib with /opt/X11/lib/libfontconfig.1.dylib, and that produced a working version.

**Comment by jeremyhu** [comment] 2021-03-15 16:35
As a hack, you could probably re-package your Gtk.framework, replacing libfontconfig.1.dylib with a symlink, but I'm not sure how well that will work.

I suspect this was done this way at the time because you maybe wanted to also support Tiger systems, and Tiger had a very old X11 install in /usr/X11.  Shipping your own userspace probably still is the right thing to do, but you need to figure out how to handle font caching at startup.  You'll need to run fc-cache at launch to ensure your font cache is up to date and of matching-version.

**Comment by jeremyhu** [comment] 2021-03-15 16:37
You probably also want to update Gtk.framework to be @rpath-relative and bundle it with your app to avoid the installation piece.  That should also let you sign / notarize you app, so it can be installed on newer systems without jumping through hoops.

**Comment by jeremyhu** [comment] 2021-03-15 16:38
GTK's Quartz backend has also matured a lot in the past decade, so you might want to try using that instead (https://www.gtk.org/docs/installations/macos/).  I suspect that would even let you distribute via the Mac App Store!

**Comment by jeremyhu** [comment] 2021-03-15 16:46
Let me know if you need any help understanding your options here, but I'm closing this out since it's not an XQuartz bug.

**Closed** 2021-03-15 16:45 UTC
Labels: Regression

**Comment by franzinc** [comment] 2021-03-15 18:29
Just catching up on all your posts...

OK.  A lot to digest.  I'll put some time into and post follow ups if I have questions.  Thanks.

**Comment by franzinc** [comment] 2021-03-15 18:31
Btw, we do sign our app.  We haven't done the notarization step yet, though.  Did you find it wasn't signed?

**Comment by franzinc** [comment] 2021-03-15 19:36
Are you going to add back libcairo?  If you did, would I just be able to then rely on the install XQuartz libraries and do away with the need for the framework?

**Comment by franzinc** [comment] 2021-03-15 19:44
Do you know what changed between 2.7.11 and 2.8.0 that broke Allegro CL?

On libcairo and using the installed XQuartz libraries: the start of the app is done via a BASH script, so I could easily supply a specific LD_LIBRARY_PATH that included the XQuartz libraries.

**Comment by jeremyhu** [comment] 2021-03-16 04:13
> Btw, we do sign our app. We haven't done the notarization step yet, though. Did you find it wasn't signed?

Ah, you're right.  The app is signed (although with an older version of codesign).  Gtk.framework is not:

```
$ pkgutil --check-signature /Applications/AllegroCL64express.app/Contents/Resources/GTK+-Framework-2.24.pkg
Package "GTK+-Framework-2.24.pkg":
   Status: no signature

$ codesign -vvv -d /Library/Frameworks/Gtk.framework
/Library/Frameworks/Gtk.framework: code object is not signed at all

```

**Comment by franzinc** [comment] 2021-03-16 16:45
I appreciate all the help you're giving us here.  If I could ask for clarifications of the previous comment.

Looks like we last built the Gtk.framework in 2016.  Can you say more where the `@rpath-relative` would be?

I'm unsure what you mean by "_your_ fc-cache".  You mean the one in effect when the framework was built?  If so, that was long, long ago. It was built with a process that used Mac Ports. Maybe that means I need to try to rebuild the framework and put that binary into the package.

I would definitely like to switch to the Quartz-based Gtk.framework.  I looked over the [docs](https://www.gtk.org/docs/installations/macos/) you pointed me to and it seems daunting.  I will look into that, though.

**Comment by jeremyhu** [comment] 2021-03-17 00:43
> Looks like we last built the Gtk.framework in 2016. Can you say more where the `@rpath-relative` would be?

You would want to iterate over the mach-o dylibs and change their install names and the names to other dylibs within the bundle.  You should use @rpath in the install name of the top-level dylib and then maybe use @loader_path or @rpath for everything else.  Your app would then specify -rpath at link time to specify an @executable_path relative path from your executable to your framework within your app bundle.  I believe GTK's bundler script does something like this for the native GTK framework, so I suggest looking at that.
 
> I'm unsure what you mean by "_your_ fc-cache". You mean the one in effect when the framework was built? 

Yes.  It gets created when you build the fontconfig library.

> If so, that was long, long ago. It was built with a process that used Mac Ports. Maybe that means I need to try to rebuild the framework and put that binary into the package.

Probably.  It might be straight forward (although manual) to *just* build fc-cache though.
