### ISSUE TITLE
When iPad connected via Sidecar -> GLXBadContext

### ISSUE THREAD

**Issue by 4doom4** [XQuartz/XQuartz#105] opened 2021-03-03 18:45 UTC
When an iPad is connected via Sidecar several OpenGL applications crash. I paste the error message of two of them:

glxgears
error: xp_attach_gl_context returned: 2
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  28
  Current serial number in output stream:  28

MOE (http://www.chemcomp.com)
error: xp_attach_gl_context returned: 2
StartFrame: glXMakeCurrent error!

**Comment by jeremyhu** [comment] 2021-03-04 06:24
Similar issues from the past:

  * https://github.com/XQuartz/xquartz-old-tickets/blob/master/ticket/512.md
  * https://github.com/XQuartz/xquartz-old-tickets/blob/master/ticket/536.md
  * https://github.com/XQuartz/xquartz-old-tickets/blob/master/ticket/766.md

**Comment by jeremyhu** [comment] 2021-03-04 06:26
Also, a developer on xquartz-devel was seeing something similar with their app.

How reproducible is this?  Can you see this with glxgears or another small GLX application to reduce some complexity in reproducing this?

**Comment by 4doom4** [comment] 2021-03-04 08:29
I used the current xquartz RC2 and you see the glxgears error in the report. It happens 100% of the time. 

1. Start xquartz
2. Open terminal within xquartz
2. Glxgears works
3. Connect iPad via cable and sidecar
4. Glxgears spits error above
5. Disconnect sidecar
6. Glxgears works

**Comment by 4doom4** [comment] 2021-03-04 08:43
Maybe the video helps:

https://user-images.githubusercontent.com/11906121/109935584-0b529200-7cce-11eb-8fe1-8a8559e5483b.mp4

**Comment by jeremyhu** [comment] 2021-03-06 05:21
Ok, thanks.  I'll give this a try.  Do you know if this ever worked with older mesa or older XQuartz?

**Comment by 4doom4** [comment] 2021-03-06 10:41
Let me uninstall 2.8 and try with 2.7. If it works I will get back to you

**Comment by jeremyhu** [comment] 2021-03-10 06:04
Be sure to check the FAQ on how to uninstall 2.8.0 before re-installing 2.7.11:
    https://www.xquartz.org/FAQs.html

You'll possibly want to reboot after the downgrade as it seems there might be some issues with getting the aqua session into an appropriate state with just a logout.

**Comment by jeremyhu** [comment] 2021-03-12 19:29
Yeah, I'm not able to trigger the issue with my Apple Silicon MacBook Air nor my 2018 Mac Mini.

My hunch is that this is specific to the discrete GPU in your system and that your system is using the integrated GPU (Intel Graphics) when sidecar is disabled and then switches to discrete (AMD Radeon) when enabled.  Can you take sidecar out of the equation and force discrete graphics (eg: use the menubar extra from https://gfx.io) to see if that triggers the issue for you?

Can you provide your system profile, so I can try tracking down similar hardware?

**Comment by 4doom4** [comment] 2021-03-12 19:52
I can't switch between integrated and dedicated graphics using this tool. It tells me that I need to first close the running glxgears application. Even if I do this it seems not to lock to integrated GPU and lock onto the dedicated GPU only. I zipped my entire System Information. Let me know if this helps.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/11906121/110991441-eb2d6d80-8374-11eb-8bec-b773bd46c0df.png">

[MacBook Pro.xml.zip](https://github.com/XQuartz/XQuartz/files/6132637/MacBook.Pro.xml.zip)

**Comment by jeremyhu** [comment] 2021-03-12 22:22
The closest system I have is a 15,3 (it has Vega 20 instead of Radeon Pro 560X) and I was unable to reproduce it with that...

I have an external Black Magic eGPU with a 560, and I cannot reproduce using that either...  so I'm on the hunt for better matching hardware.

**Comment by 4doom4** [comment] 2021-03-12 22:34
If I can debug anything let me know.

**Comment by jeremyhu** [comment] 2023-01-27 05:49
Can you reproduce this, then capture a sysdiagnose by running `sudo sysdiagnose`.  Then, file a bug report at http://bugreport.apple.com with it attached.  Please reference this ticket in that bug report and also add a comment here with the FB number.  Thanks.

**Comment by ctx-mebert** [comment] 2023-02-21 15:16
@jeremyhu I tried it again in macOS 13.2 (22D49) with xQuartz 2.8.5 (xorg-server 21.1.6) and I can't reproduce the issue anymore. Sorry maybe it got fixed by something.

**Comment by 4doom4** [comment] 2023-02-21 15:17
@jeremyhu I tried it again in macOS 13.2 (22D49) with xQuartz 2.8.5 (xorg-server 21.1.6) and I can't reproduce the issue anymore. Sorry maybe it got fixed by something.

**Comment by jeremyhu** [comment] 2023-02-21 16:48
Great.  It was probably fixed in a macOS update.  Thanks.

**Comment by jeremyhu** [comment] 2023-02-21 16:48
Great.  It was probably fixed in a macOS update.  Thanks.

**Closed** 2023-02-21 16:50 UTC
Labels: macOS, GLX
